# Generated by Django 5.1.4 on 2025-01-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brushbazaarproducts',
            old_name='content',
            new_name='artist',
        ),
    ]
